FROM node:8.10-alpine

RUN apk --no-cache add nginx

WORKDIR /app

COPY ./package.json /app/

RUN npm install

COPY . /app/

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /run/nginx

RUN npm run build \
  && rm -fr /var/www/html/ \
  && ln -s /app/dist /var/www/html

EXPOSE 80

CMD ["nginx","-g","daemon off;"]
